version: '3'
services:
  backend:
    container_name: Backend
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    ports:
      - '5000:5000'
    depends_on:
      - mockifymongo
      - redis

  mockifymongo:
    container_name: mockifymongo
    image: 'mongo:latest'
    ports:
      - '27018:27017'

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6378:6379"
    volumes:
      - redis:/root/redis
    env_file:
      - ./server/.env
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
      
networks:
  mockify:
    driver: bridge

volumes:
  redis: