version: '3'
services:
  nginx:
    container_name: ReverseProxy
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    restart: always
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - client
      - backend
      - landing
      - mongo

  backend:
    container_name: Backend
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    ports:
      - '5000:5000'
    depends_on:
      - mongo

  client:
    container_name: admin
    stdin_open: true
    env_file:
      - ./client/.env
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3007:3007'
    environment:
      - CHOKIDAR_USEPOLLING=true
  #  important : comment landing block out for deploying self-managed mockify
  landing:
    container_name: landing
    stdin_open: true
    build:
      context: ./landing
      dockerfile: Dockerfile

    ports:
      - '3006:3006'
    environment:
      - CHOKIDAR_USEPOLLING=true


  mongo:
    image: 'mongo:latest'
    volumes:
      - mongo_volume:/data/mockify
    ports:
      - '27017:27017'
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email araldhafeeri@mockify.io --agree-tos --no-eff-email --force-renewal -d mockify.io  -d www.mockify.io -d www.api.mockify.io -d api.mockify.io -d www.admin.mockify.io -d admin.mockify.io -d beta.mockify.io -d www.beta.mockify.io
networks:
  default:
    driver: bridge

volumes:
  mongo_volume:
    external: true
  certbot-etc:
  certbot-var:
  web-root:
  dhparam:
