version: '3'
services:
  nginx:
    container_name: ReverseProxy
    image: nginx:latest
    ports:
      - '80:80'
    build:
      context: ./dev
      dockerfile: Dockerfile
    depends_on:
      - backend
      - landing
      - mongo
  backend:
    container_name: Backend
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    ports:
      - '5000:5000'
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: 'mongo:latest'
    ports:
      - '27017:27017'

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/root/redis
    env_file:
      - ./server/.env
    command: redis-server --requirepass {REDIS_PASSWORD} --appendonly yes
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
      
networks:
  default:
    driver: bridge

volumes:
  redis:
