export const ROUTES_NAMES = {
   LOGIN: '/login',
   USER: '/user',
   DASHBOARD: '/dashboard',
   PROJECT: '/project',
   RESOURCE: '/resource',
   DATA: '/data',
   POLICY: '/policy',
   ROOT: '/',
   ENDPOINT: '/endpoint',
   EDGE: '/edge',
   SWAGGER: '/swagger',
   CACHE: '/cache',
   EVENT: '/event',
   CONFIG: '/config',
   CLIENTS: '/config/clients',
}